version: '3.9'

services:
  os_base:
      image: os_base:latest
      build:
        context: ./
        dockerfile: os_base.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
      env_file:
        - path: ./default.env
          required: true # default
      networks:
        - pgsql_bridge
  messenger:
      tty: true
      restart: unless-stopped
      image: messenger:latest
      build:
        context: ./
        dockerfile: messenger.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - APP=${APP}
      # network_mode: host
      depends_on:
        - postgres_db
      ports:
          - "9087:9087"
      env_file:
        - path: ./default.env
          required: true # default
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.2
  postgres_db:
      tty: true
      restart: unless-stopped
      image: postgres_db:latest
      build:
        context: ./
        dockerfile: postgres_db.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - PGPASSWORD=${PGPASSWORD}
      # network_mode: host
      ports:
          - "5435:5435"
      env_file:
        - path: ./default.env
          required: true # default
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.3
  monitoring_server:
      tty: true
      restart: unless-stopped
      image: monitoring_server:latest
      build:
        context: ./
        dockerfile: monitoring_server.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - PGPASSWORD=${PGPASSWORD}
      # network_mode: host
      depends_on:
        - postgres_db
      ports:
          - "8080:8080"
      env_file:
        - path: ./default.env
          required: true # default
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.4
      

networks:
  pgsql_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: "192.167.1.0/24"
          gateway: "192.167.1.1"
