services:
  os_base:
      image: os_base:latest
      entrypoint: ["/usr/bin/true"]
      network_mode: host
      build:
        context: ./
        dockerfile: os_base.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
      env_file: ./default.env
  load_balancer:
      tty: true
      restart: unless-stopped
      image: load_balancer:latest
      build:
        context: ./
        dockerfile: load_balancer.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
      # network_mode: host
      ports:
        - "80:80"
      env_file: ./default.env
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.10
      depends_on:
        - os_base
  messenger:
      tty: true
      restart: unless-stopped
      image: messenger:latest
      build:
        context: ./
        dockerfile: messenger.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - APP=${APP}
          - SPRING_PROPERTY=${SPRING_PROPERTY}
      # network_mode: host
      depends_on:
        - postgres_db
        - kafka
      ports:
          - "9087:9087"
      env_file: ./default.env
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.2
  postgres_db:
      tty: true
      restart: unless-stopped
      image: postgres_db:latest
      build:
        context: ./
        dockerfile: postgres_db.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - PGPASSWORD=${PGPASSWORD}
      # network_mode: host
      ports:
        - "5435:5435"
      env_file: ./default.env
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.3
      depends_on:
        - os_base

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
    networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.6
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.167.1.6:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.167.1.5:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  monitoring_server:
      tty: true
      restart: unless-stopped
      image: monitoring_server:latest
      build:
        context: ./
        dockerfile: monitoring_server.Dockerfile
        args:
          - SERVICEPATH=${SERVICEPATH}
          - INSTALLPATH=${INSTALLPATH}
          - BINPATH=${BINPATH}
          - PGPASSWORD=${PGPASSWORD}
      # network_mode: host
      depends_on:
        - postgres_db
      ports:
          - "8080:8080"
      env_file: ./default.env
      networks:
        pgsql_bridge:
          ipv4_address: 192.167.1.4

networks:
  pgsql_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: "192.167.1.0/24"
          gateway: "192.167.1.1"
